version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
